# Site settings

title: Destructive Voice
description: a CTF team from Ural Federal University, Yekaterinburg
email: destructivevoice@gmail.com
baseurl: ''
favicon: /favicon.png

permalink: /:categories

twitter_username: dvteam_org
ctftime_team_id: 7527

# google analytics
# google_analytics_id : UA-53386152-2

# disqus_short_name: maangalabscom
# disqus_show_comment_count: true

# Build settings

markdown: kramdown

authors:
  hx:
    display_name: Alexander Borzunov
    email: borzunov.alexander@gmail.com
    github: borzunov
  phil9l:
    display_name: Phil Bazun
    email: Phil9lne@gmail.com
    github: Phil9l
