# Site settings

title: Destructive Voice
description: a CTF team from Ural Federal University, Yekaterinburg
email: pranav@maangalabs.com
baseurl: /dvteam.org
favicon: /favicon.png

permalink: /:categories/:title

twitter_username: pranavrajs

# google analytics
# google_analytics_id : UA-53386152-2

# disqus_short_name: maangalabscom
# disqus_show_comment_count: true

# Build settings

markdown: kramdown

authors:
  hx:
    display_name: Alexander Borzunov
    email: borzunov.alexander@gmail.com
    github: borzunov
